// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMCf1X7_xcq2SQ3NvcWU7zN7KVeJCwsAo',
    appId: '1:621179872034:web:73b7542cd61f17c2d3bb7b',
    messagingSenderId: '621179872034',
    projectId: 'svu-wmb',
    authDomain: 'svu-wmb.firebaseapp.com',
    storageBucket: 'svu-wmb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQjv6LvZ7BBjb2zEY7Po0kqkea-WTwT8s',
    appId: '1:621179872034:android:5151689f26d1cda7d3bb7b',
    messagingSenderId: '621179872034',
    projectId: 'svu-wmb',
    storageBucket: 'svu-wmb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMwek3o439JIlLfA3JGqSQzlcWrDMv5I4',
    appId: '1:621179872034:ios:5b0c0eb7bb100829d3bb7b',
    messagingSenderId: '621179872034',
    projectId: 'svu-wmb',
    storageBucket: 'svu-wmb.appspot.com',
    iosBundleId: 'com.example.homeWork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMwek3o439JIlLfA3JGqSQzlcWrDMv5I4',
    appId: '1:621179872034:ios:a922f348249caa8dd3bb7b',
    messagingSenderId: '621179872034',
    projectId: 'svu-wmb',
    storageBucket: 'svu-wmb.appspot.com',
    iosBundleId: 'com.example.homeWork.RunnerTests',
  );
}
